spring.application.name=desafio-bancao

# -- Actuator Configuration --

# Expose specific actuator endpoints over the web
management.endpoints.web.exposure.include=health,info,prometheus,metrics,loggers

# Show detailed health information (consider security implications in production)
management.endpoint.health.show-details=always

# Optional: Add custom application info (Example)
# info.app.name=${spring.application.name}
# info.app.description=API para gerenciamento de transações bancárias
# info.app.version=@project.version@ # Requires build plugin like gradle-git-properties or maven resource filtering
